export * from './icons/ArrowLeftIcon.tsx';
export * from './icons/AvatarIcon.tsx';
export * from './icons/AvatarFillIcon.tsx';
export * from './icons/DashboardIcon.tsx';
export * from './icons/DashboardFillIcon.tsx';
export * from './icons/FoodIcon.tsx';
export * from './icons/FoodFillIcon.tsx';
export * from './icons/RecipeIcon.tsx';
export * from './icons/RecipeFillIcon.tsx';
